version: "3.4"

services:
  mongo:
    image: mongo:4.2.8-bionic
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: daga-iot
    volumes:
      - ./persistencyMongo:/data/db
    networks:
      - red
    ports:
      - "27017:27017"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - red
    ports:
      - "7203:7203"
    depends_on:
      - "mongo"


networks:
  red:
